[package]
name = "apollo-parser"
version = "0.1.0"
authors = ["Irina Shestak <shestak.irina@gmail.com>"]
description = "Saving this crate name for future parser use."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rowan = "0.13.0-pre.7"
