[package]
name = "apollo-smith"
version = "0.1.0"
authors = ["Irina Shestak <shestak.irina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = "1.0.0"